source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HRRoundAndBorderedView_Example', :exclusive => true do
  pod 'HRRoundAndBorderedView', :path => '../'
end

target 'HRRoundAndBorderedView_Tests', :exclusive => true do
  pod 'HRRoundAndBorderedView', :path => '../'

  
end
